name = "FIJRegistry"
uuid = "c234bb31-458f-496e-a9fd-a460372d4fe2"
repo = "git@github.com:f-ij/FIJRegistry.git"
description = "Private Registry for my packages"

[packages]
6a369836-0793-447d-b7ee-625716f2d05b = { name = "Processes", path = "P/Processes" }
